### ISSUE TITLE
when i try to install pyre i get error

### ISSUE THREAD

**Issue by Av1zi** [Amp63/pyre#1]
![image](https://github.com/Amp63/pyre/assets/137340642/12920a33-a721-40f2-9905-23f1ecdd70c6)
![image](https://github.com/Amp63/pyre/assets/137340642/4d4d8829-ca49-4cfe-9a8d-036393617c3f)

welp?

**Comment by Amp63** [comment]
Try installing wheel with `pip install wheel` then install pyre again.

**Comment by Av1zi** [comment]
Nope :(
![image](https://github.com/Amp63/pyre/assets/137340642/76984c59-bdc0-43b3-ba93-906567c430a6)
![image](https://github.com/Amp63/pyre/assets/137340642/0cf1f5c8-fa6b-437f-a0c8-b1f18dee9e21)
![image](https://github.com/Amp63/pyre/assets/137340642/5506230a-22d2-46ee-9859-b1c1b84b6ec7)

**Comment by Amp63** [comment]
Dang. Well, I'm currently moving from setup.py into poetry, so hopefully that will fix any installation issues. Sorry bout that

**Comment by Av1zi** [comment]
np just tell me when u fix it

**Comment by Amp63** [comment]
Alright, hopefully it's fixed now. Just added the newest version to pypi

**Comment by Av1zi** [comment]
Sadly it still buggy 😭 
![image](https://github.com/Amp63/pyre/assets/137340642/782cb3a2-be48-4fc3-a04f-5f49c7f479f0)
![image](https://github.com/Amp63/pyre/assets/137340642/d68804ff-549e-4b69-938e-db3f8fdb8377)

**Comment by Av1zi** [comment]
i dont know much abut Python but i think there is possibly a missing file? named "tool.setup_scm"

**Comment by Amp63** [comment]
Ah, you’re installing the wrong module. It’s `pip install dfpyre` not `pyre`. sorry, will make that clearer

**Comment by Av1zi** [comment]
al good it be working now

TYSM
![image](https://github.com/Amp63/pyre/assets/137340642/42275e80-ab3f-48b2-96a6-6e5805eb3c88)
